#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tiffany Tse 

# Short bio or description (displayed in the header)
description: Web Developer, Designer and Teacher

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: tiffanytse
  email: hey@tiffanytse.ca
  github: tiffanytse
  linkedin: tiffanyjtse
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: tiffany_tse

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-37748294-1

# Your website URL 
# Used for Sitemap.xml and your RSS feed
url: www.tiffanytse.ca

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/tiffanytse.ca"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: sass
  style: :compressed #expanded # You might prefer to minify using 

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - scss/*
    - config.rb
